config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_scenario
      delete :remove_events
      delete :memory, action: :destroy_memory
    end

    collection do
      put :toggle_visibility
      post :propagate
      get :type_details
      get :event_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end

    resources :events, :only => [:index]

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resource :diagram, :only => [:show]

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :scenarios do
    collection do
      resource :scenario_imports, :only => [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
    end

    resource :diagram, :only => [:show]
  end

  resources :user_credentials, :except => :show do
    collection do
      post :import
    end
  end

  resources :services, :only => [:index, :destroy] do
    member do
      post :toggle_availability
    end
  end

  resources :jobs, :only => [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get "/worker_status" => "worker_status#show"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests, :via => [:get, :post, :put, :delete]
  post  "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy
  post  "/users/:user_id/update_location/:secret" => "web_requests#update_location" # legacy

  devise_for :users,
             controllers: { 
               omniauth_callbacks: 'omniauth_callbacks',
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "/about" => "home#about"
  root :to => "home#index"
end

app/models/service.rb
class Service < ActiveRecord::Base
  serialize :options, Hash

  belongs_to :user, :inverse_of => :services
  has_many :agents, :inverse_of => :service

  validates_presence_of :user_id, :provider, :name, :token

  before_destroy :disable_agents

  scope :available_to_user, lambda { |user| where("services.user_id = ? or services.global = true", user.id) }
  scope :by_name, lambda { |dir = 'desc'| order("services.name #{dir}") }

  def disable_agents(conditions = {})
    agents.where.not(conditions[:where_not] || {}).each do |agent|
      agent.service_id = nil
      agent.disabled = true
      agent.save!(validate: false)
    end
  end

  def toggle_availability!
    disable_agents(where_not: {user_id: self.user_id}) if global
    self.global = !self.global
    self.save!
  end

  def prepare_request
    if expires_at && Time.now > expires_at
      refresh_token!
    end
  end

  def refresh_token!
    response = HTTParty.post(endpoint, query: {
                  type:          'refresh',
                  client_id:     oauth_key,
                  client_secret: oauth_secret,
                  refresh_token: refresh_token
    })
    data = JSON.parse(response.body)
    update(expires_at: Time.now + data['expires_in'], token: data['access_token'], refresh_token: data['refresh_token'].presence || refresh_token)
  end

  def endpoint
    client_options = "OmniAuth::Strategies::#{OmniAuth::Utils.camelize(self.provider)}".constantize.default_options['client_options']
    URI.join(client_options['site'], client_options['token_url'])
  end

  def oauth_key
    (config = Devise.omniauth_configs[provider.to_sym]) && config.args[0]
  end

  def oauth_secret
    (config = Devise.omniauth_configs[provider.to_sym]) && config.args[1]
  end

  def self.initialize_or_update_via_omniauth(omniauth)
    options = get_options(omniauth)

    find_or_initialize_by(provider: omniauth['provider'], uid: omniauth['uid'].to_s).tap do |service|
      service.assign_attributes token: omniauth['credentials']['token'],
                                secret: omniauth['credentials']['secret'],
                                name: options[:name],
                                refresh_token: omniauth['credentials']['refresh_token'],
                                expires_at: omniauth['credentials']['expires_at'] && Time.at(omniauth['credentials']['expires_at']),
                                options: options
    end
  end

  def self.register_options_provider(provider_name, &block)
    option_providers[provider_name] = block
  end

  def self.get_options(omniauth)
    option_providers.fetch(omniauth['provider'], option_providers['default']).call(omniauth)
  end

  private
  @@option_providers = HashWithIndifferentAccess.new
  cattr_reader :option_providers

  register_options_provider('default') do |omniauth|
    {name: omniauth['info']['nickname'] || omniauth['info']['name']}
  end

  register_options_provider('37signals') do |omniauth|
    {user_id: omniauth['extra']['accounts'][0]['id'], name: omniauth['info']['name']}
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  include SortableTable

  before_action :upgrade_warning, only: :index

  def index
    set_table_sort sorts: %w[provider name global], default: { provider: :asc }

    @services = current_user.services.reorder(table_sort).page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @services }
    end
  end

  def destroy
    @services = current_user.services.find(params[:id])
    @services.destroy

    respond_to do |format|
      format.html { redirect_to services_path }
      format.json { head :no_content }
    end
  end

  def toggle_availability
    @service = current_user.services.find(params[:id])
    @service.toggle_availability!

    respond_to do |format|
      format.html { redirect_to services_path }
      format.json { render json: @service }
    end
  end
end

app/views/services/index.html.erb
<% content_for :title, "Services" -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>
          Your Services
        </h2>
      </div>
      <p>
        Before you can authenticate with a service, you need to set it up. Have a look at the Huginn
        <%= link_to 'wiki', 'https://github.com/huginn/huginn/wiki/Configuring-OAuth-applications', target: :_blank %>
        for guidance.
      </p>
      <%- Devise.omniauth_providers.each { |provider| -%>
        <p><%= omniauth_button(provider) %></p>
      <%- } -%>
      <hr>

      <div class='table-responsive'>
        <table class='table table-striped events'>
          <tr>
            <th><%= sortable_column 'provider', 'asc' %></th>
            <th><%= sortable_column 'name', 'asc' %></th>
            <th><%= sortable_column 'global', name: 'Global?' %></th>
            <th></th>
          </tr>

        <% @services.each do |service| %>
          <tr>
            <td><%= omniauth_provider_name(service.provider) %></td>
            <td><%= service.name %></td>
            <td><%= yes_no(service.global) %></td>
            <td>
              <div class="btn-group btn-group-xs">
                <% if service.global %>
                  <%= link_to 'Make private', toggle_availability_service_path(service), method: :post, data: { confirm: 'Are you sure you want to remove access to your data on this service for other users?'}, class: "btn btn-default" %>
                <% else %>
                   <%= link_to 'Make global', toggle_availability_service_path(service), method: :post, data: { confirm: 'Are you sure you want to grant every user on this system access to your data on this service?'}, class: "btn btn-default" %>
                <% end %>
                <%= link_to 'Delete', service_path(service), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-danger" %>
              </div>
            </td>
          </tr>
        <% end %>
        </table>
      </div>

      <%= paginate @services, :theme => 'twitter-bootstrap-3' %>
    </div>
  </div>
</div>