config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_scenario
      delete :remove_events
      delete :memory, action: :destroy_memory
    end

    collection do
      put :toggle_visibility
      post :propagate
      get :type_details
      get :event_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end

    resources :events, :only => [:index]

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resource :diagram, :only => [:show]

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :scenarios do
    collection do
      resource :scenario_imports, :only => [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
    end

    resource :diagram, :only => [:show]
  end

  resources :user_credentials, :except => :show do
    collection do
      post :import
    end
  end

  resources :services, :only => [:index, :destroy] do
    member do
      post :toggle_availability
    end
  end

  resources :jobs, :only => [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get "/worker_status" => "worker_status#show"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests, :via => [:get, :post, :put, :delete]
  post  "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy
  post  "/users/:user_id/update_location/:secret" => "web_requests#update_location" # legacy

  devise_for :users,
             controllers: { 
               omniauth_callbacks: 'omniauth_callbacks',
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "/about" => "home#about"
  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :upgrade_warning, only: :index

  def index
  end

  def about
  end
end

app/views/home/_signed_in_index.html.erb
<div class='container'>

  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>Welcome to Huginn!</h2>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-6'>
      <p>
        You have created <span class="text-success"><%= pluralize current_user.agents.count, "agent" %></span>.
      </p>
      <p>
        <%= link_to 'View <i class="icon-chevron-right"></i>'.html_safe, agents_path, class: "btn btn-primary" %>
      </p>
    </div>
    <div class='col-md-6'>
      <p>
        Your agents have recorded
        <span class="text-success"><%= pluralize current_user.events.recent.count, "event" %> recently</span> and
        <span class=""><%= pluralize current_user.events.count, 'event' %> in total</span>.
      </p>
      <p>
        <%= link_to 'View <i class="icon-chevron-right"></i>'.html_safe, events_path, class: "btn btn-primary" %>
      </p>
    </div>
  </div>

  <div class='row' style='min-height: 250px'></div>

  <div class='row'>
    <div class='col-md-10'>
      <blockquote>
        <p>...two ravens named Huginn and Muninn sit on Odin's shoulders. The ravens tell Odin everything they see and
          hear. Odin sends Huginn and Muninn out at dawn, and the birds fly all over the world before returning at
          dinner-time. As a result, Odin is kept informed of many events.</p>
          <small><a href="http://en.wikipedia.org/wiki/Huginn_and_Muninn">Wikipedia</a>, in reference to
            <em>Gylfaginning</em></small>
      </blockquote>
    </div>
    <div class='col-md-2'>
      <%= image_tag 'odin.jpg', :class => 'img-responsive img-rounded', :title => "Wägner, Wilhelm. 1882. Nordisch-germanische Götter und Helden. Otto Spamer, Leipzig & Berlin. Page 7." %>
    </div>
  </div>

</div>

app/views/home/_signed_out_index.html.erb
<div class='container'>
  
  <div class='row'>
    
    <div class="col-md-4 col-md-offset-2">
      <h1>Your agents are standing by</h1>
      <p>Huginn monitors the world and acts on your behalf.</p>

      <%= link_to "Login", new_user_session_path, :class => "btn btn-large" %>
      <%= link_to "Signup", new_user_registration_path, :class => "btn btn-primary btn-large" %>
    </div>
    
    <div class="col-md-3 col-md-offset-1">
      <%= image_tag 'odin.jpg', :class => 'img-responsive img-rounded', :title => "Wägner, Wilhelm. 1882. Nordisch-germanische Götter und Helden. Otto Spamer, Leipzig & Berlin. Page 7." %>
    </div>
  
  </div>

</div>

app/views/home/about.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h1>Example page header</h1>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= render "signed_in_index" %>
<% else %>
  <%= render "signed_out_index" %>
<% end %>