config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_scenario
      delete :remove_events
      delete :memory, action: :destroy_memory
    end

    collection do
      put :toggle_visibility
      post :propagate
      get :type_details
      get :event_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end

    resources :events, :only => [:index]

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resource :diagram, :only => [:show]

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :scenarios do
    collection do
      resource :scenario_imports, :only => [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
    end

    resource :diagram, :only => [:show]
  end

  resources :user_credentials, :except => :show do
    collection do
      post :import
    end
  end

  resources :services, :only => [:index, :destroy] do
    member do
      post :toggle_availability
    end
  end

  resources :jobs, :only => [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get "/worker_status" => "worker_status#show"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests, :via => [:get, :post, :put, :delete]
  post  "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy
  post  "/users/:user_id/update_location/:secret" => "web_requests#update_location" # legacy

  devise_for :users,
             controllers: { 
               omniauth_callbacks: 'omniauth_callbacks',
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "/about" => "home#about"
  root :to => "home#index"
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  include HasGuid

  belongs_to :user, :counter_cache => :scenario_count, :inverse_of => :scenarios
  has_many :scenario_memberships, :dependent => :destroy, :inverse_of => :scenario
  has_many :agents, :through => :scenario_memberships, :inverse_of => :scenarios

  validates_presence_of :name, :user

  validates_format_of :tag_fg_color, :tag_bg_color,
    # Regex adapted from: http://stackoverflow.com/a/1636354/3130625
    :with => /\A#(?:[0-9a-fA-F]{3}){1,2}\z/, :allow_nil => true,
    :message => "must be a valid hex color."

  validate :agents_are_owned

  def destroy_with_mode(mode)
    case mode
    when 'all_agents'
      Agent.destroy(agents.pluck(:id))
    when 'unique_agents'
      Agent.destroy(unique_agent_ids)
    end

    destroy
  end

  def self.icons
    @icons ||= begin
      YAML.load_file(Rails.root.join('config/icons.yml'))
    end
  end

  private

  def unique_agent_ids
    agents.joins(:scenario_memberships)
          .group('scenario_memberships.agent_id')
          .having('count(scenario_memberships.agent_id) = 1')
          .pluck('scenario_memberships.agent_id')
  end

  def agents_are_owned
    unless agents.all? { |s| s.user == user }
      errors.add(:agents, 'must be owned by you')
    end
  end
end

app/controllers/scenarios_controller.rb
require 'agents_exporter'

class ScenariosController < ApplicationController
  include SortableTable
  skip_before_action :authenticate_user!, only: :export

  def index
    set_table_sort sorts: %w[name public], default: { name: :asc }

    @scenarios = current_user.scenarios.reorder(table_sort).page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @scenarios }
    end
  end

  def new
    @scenario = current_user.scenarios.build

    respond_to do |format|
      format.html
      format.json { render json: @scenario }
    end
  end

  def show
    @scenario = current_user.scenarios.find(params[:id])

    set_table_sort sorts: %w[name last_check_at last_event_at last_receive_at], default: { name: :asc }
    @agents = @scenario.agents.preload(:scenarios, :controllers).reorder(table_sort).page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @scenario }
    end
  end

  def share
    @scenario = current_user.scenarios.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @scenario }
    end
  end

  def export
    @scenario = Scenario.find(params[:id])
    raise ActiveRecord::RecordNotFound unless @scenario.public? || (current_user && current_user.id == @scenario.user_id)

    @exporter = AgentsExporter.new(name: @scenario.name,
                                   description: @scenario.description,
                                   guid: @scenario.guid,
                                   tag_fg_color: @scenario.tag_fg_color,
                                   tag_bg_color: @scenario.tag_bg_color,
                                   icon: @scenario.icon,
                                   source_url: @scenario.public? && export_scenario_url(@scenario),
                                   agents: @scenario.agents)
    response.headers['Content-Disposition'] = 'attachment; filename="' + @exporter.filename + '"'
    render :json => JSON.pretty_generate(@exporter.as_json)
  end

  def edit
    @scenario = current_user.scenarios.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @scenario }
    end
  end

  def create
    @scenario = current_user.scenarios.build(scenario_params)

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'This Scenario was successfully created.' }
        format.json { render json: @scenario, status: :created, location: @scenario }
      else
        format.html { render action: "new" }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @scenario = current_user.scenarios.find(params[:id])

    respond_to do |format|
      if @scenario.update_attributes(scenario_params)
        format.html { redirect_to @scenario, notice: 'This Scenario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  def enable_or_disable_all_agents
    @scenario = current_user.scenarios.find(params[:id])

    @scenario.agents.update_all(disabled: params[:scenario][:disabled] == 'true')
    respond_to do |format|
      format.html { redirect_to @scenario, notice: 'The agents in this scenario have been successfully updated.' }
      format.json { head :no_content }
    end
  end

  def destroy
    @scenario = current_user.scenarios.find(params[:id])
    @scenario.destroy_with_mode(params[:mode])

    respond_to do |format|
      format.html { redirect_to scenarios_path }
      format.json { head :no_content }
    end
  end

  private

  def scenario_params
    params.require(:scenario).permit(:name, :description, :public, :source_url,
                                     :tag_fg_color, :tag_bg_color, :icon, agent_ids: [])
  end
end

app/helpers/scenario_helper.rb
module ScenarioHelper

  def style_colors(scenario)
    colors = {
      color: scenario.tag_fg_color || default_scenario_fg_color,
      background_color: scenario.tag_bg_color || default_scenario_bg_color
    }.map { |key, value| "#{key.to_s.dasherize}:#{value}" }.join(';')
  end

  def scenario_label(scenario, text = nil)
    text ||= scenario.name
    content_tag :span, text, class: 'label scenario', style: style_colors(scenario)
  end

  def default_scenario_bg_color
    '#5BC0DE'
  end

  def default_scenario_fg_color
    '#FFFFFF'
  end

end

app/views/scenarios/_confirm_deletion_modal.html.erb
<div id="confirm-scenario-deletion-<%= scenario.id %>" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for(scenario, url: scenario_path(scenario), method: :delete) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title">
            <% if @scenario && @scenario == scenario %>
              How do you want to delete this Scenario?
            <% else %>
              How do you want to delete the Scenario '<%= scenario.name %>'?
            <% end %>
          </h4>
        </div>
        <div class="modal-body">
          <div class="radio">
            <%= label_tag do %>
              <%= radio_button_tag :mode, '', true %>
              <h4><span class="label label-success">Scenario only</span></h4>
              Only delete the Scenerio, keep the Agents.
            <% end %>
          </div>
          <div class="radio">
            <%= label_tag do %>
              <%= radio_button_tag :mode, :unique_agents %>
              <h4><span class="label label-warning">Scenario and unique Agents</span></h4>
              Also deletes Agents that are used in this Scenario only.
            <% end %>
          </div>
          <div class="radio">
            <%= label_tag do %>
              <%= radio_button_tag :mode, :all_agents %>
              <h4><span class="label label-danger">Scenario and all included Agents</span></h4>
              Deletes Scenario and all included Agents, even if they are used in different Scenarios.
            <% end %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.button 'Cancel', class: 'btn btn-default', 'data-dismiss' => 'modal' %>
          <%= f.submit 'Delete', class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/scenarios/_enable_agents_modal.html.erb
<div id="enable-disable-agents" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="enableAgentLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Confirm</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <%= form_for(scenario, as: :scenario, url: enable_or_disable_all_agents_scenario_path(scenario), method: 'PUT') do |f| %>
          <%= f.hidden_field :disabled, value: '', id: "scenario-disabled-value" %>
          <%= f.button 'No', class: 'btn btn-default', 'data-dismiss' => 'modal' %>
          <%= f.submit 'Yes', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/_form.html.erb
<%= form_for(@scenario, :method => @scenario.new_record? ? "POST" : "PUT") do |f| %>
  <% if @scenario.errors.any? %>
    <div class="row well">
      <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this Scenario from being saved:</h2>
      <% @scenario.errors.full_messages.each do |msg| %>
        <p class='text-warning'><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control', :placeholder => "Name your Scenario" %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :tag_bg_color, "Tag Background Color" %>
        <%= f.color_field :tag_bg_color, :class => 'form-control', :value => @scenario.tag_bg_color || default_scenario_bg_color %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :tag_fg_color, "Tag Foreground Color" %>
        <%= f.color_field :tag_fg_color, :class => 'form-control', :value => @scenario.tag_fg_color || default_scenario_fg_color %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.label :description, "Optional Description" %>
        <%= f.text_area :description, :rows => 10, :class => 'form-control', :placeholder => "Optionally describe what this Scenario will do.  If this will be public, you should also include some contact information." %>
      </div>

      <div class="checkbox">
        <%= f.label :public do %>
          <%= f.check_box :public %> Share this Scenario publicly
        <% end %>
        <span class="glyphicon glyphicon-question-sign hover-help" data-content="When selected, this Scenario and all Agents in it will be made public.  An export URL will be available to share with other Huginn users.  Be very careful that you do not have secret credentials stored in these Agents' options.  Instead, use Credentials by reference."></span>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <div>
          <%= f.label :icon %>
          <%= f.select(:icon, options_for_select(Scenario.icons, @scenario.icon), {},
            {:style => "font-family:'FontAwesome', Arial;", :class => 'select2-fountawesome-icon'}) %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <div>
          <%= f.label :agents %>
          <%= f.select(:agent_ids,
                       options_for_select(current_user.agents.pluck(:name, :id), @scenario.agent_ids),
                       {}, { :multiple => true, :size => 5, :class => 'select2-linked-tags form-control', data: {url_prefix: '/agents'} }) %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class='form-actions' style='clear: both'>
        <%= f.submit "Save Scenario", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/scenarios/edit.html.erb
<% content_for :title, "Edit " + @scenario.name -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>
          Edit Scenario
        </h2>
      </div>

      <%= render 'form' %>

      <hr>

      <div class="row">
        <div class="col-md-12">
          <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, scenarios_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/index.html.erb
<% content_for :title, "Scenarios" -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>
          Your Scenarios
        </h2>
      </div>

      <blockquote>Scenarios are named groups of Agents.  Scenarios allow you to organize your agents,
        and to import and export sets of Agents to share.</blockquote>

      <table class='table table-striped'>
        <tr>
          <th><%= sortable_column 'name', 'asc' %></th>
          <th>Agents</th>
          <th><%= sortable_column 'public' %></th>
          <th></th>
        </tr>

        <% @scenarios.each do |scenario| %>
          <tr>
            <td>
              <% if scenario.icon.blank? %>
                <%= scenario_label(scenario, icon('gear'))%>
              <% else %>
                <%= scenario_label(scenario, icon(scenario.icon))%>
              <% end %>
              <%= link_to(scenario.name, scenario) %>
            </td>
            <td><%= link_to pluralize(scenario.agents.count, "agent"), scenario %></td>
            <td><%= scenario.public? ? "yes" : "no" %></td>
            <td>
              <div class="btn-group btn-group-xs" style="float: right">
                <%= link_to 'Show', scenario, class: "btn btn-default" %>
                <%= link_to 'Edit', edit_scenario_path(scenario), class: "btn btn-default" %>
                <%= link_to 'Share', share_scenario_path(scenario), class: "btn btn-default" %>
                <%= link_to 'Delete', '#', data: { toggle: 'modal', target: "#confirm-scenario-deletion-#{scenario.id}"}, class: "btn btn-default" %>
              </div>
              <%= render 'scenarios/confirm_deletion_modal', scenario: scenario %>
            </td>
          </tr>
        <% end %>
      </table>

      <%= paginate @scenarios, :theme => 'twitter-bootstrap-3' %>

      <br/>

      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-plus') + ' New Scenario'.html_safe, new_scenario_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-cloud-upload') + ' Import Scenario'.html_safe, new_scenario_imports_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>
          Create a new Scenario
        </h2>
      </div>

      <%= render 'form' %>

      <hr>

      <div class="row">
        <div class="col-md-12">
          <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, scenarios_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/share.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>Share <%= scenario_label(@scenario) %> with the world</h2>
      </div>

      <p>
        <strong>Please be sure that none of the Agents in this Scenario have sensitive data in their settings before sharing!</strong>
      </p>

      <% if @scenario.public? %>
        <p>
          This Scenario is public.  You can <%= link_to "download and share your export file", export_scenario_path(@scenario, :format => :json) %>, or give out this URL:
        </p>

        <form onsubmit='return false;'>
          <input type='text' class='form-control' value='<%= export_scenario_url(@scenario, :format => :json) %>' onclick="return this.select();"/>
        </form>
      <% else %>
        This Scenario is not public.  You can share it by <%= link_to "downloading and sharing your export file", export_scenario_path(@scenario, :format => :json) %>.
      <% end %>

      <hr>

      <div class="row">
        <div class="col-md-12">
          <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, scenario_path(@scenario), class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/show.html.erb
<% content_for :title, @scenario.name -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2><%= scenario_label(@scenario) %> <%= "Public" if @scenario.public? %> Scenario</h2>

      </div>

      <% if @scenario.description.present? %>
        <blockquote><%= markdown(@scenario.description) %></blockquote>
      <% end %>

      <%= render 'agents/table', :return_to => scenario_path(@scenario) %>

      <br/>

      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', scenarios_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-plus') + ' New Agent', new_agent_path(scenario_id: @scenario.id, return: request.path), class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-random') + ' View Diagram', scenario_diagram_path(@scenario), class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-edit') + ' Edit', edit_scenario_path(@scenario), class: "btn btn-default" %>
        <% if @scenario.source_url.present? %>
          <%= link_to icon_tag('glyphicon-refresh') + ' Update', new_scenario_imports_path(url: @scenario.source_url), class: "btn btn-default" %>
        <% end %>
        <%= link_to icon_tag('glyphicon-share-alt') + ' Share', share_scenario_path(@scenario), class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-trash') + ' Delete', '#', data: { toggle: 'modal', target: "#confirm-scenario-deletion-#{@scenario.id}"}, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-play') + 'Enable all Agents', '#', data: { toggle: 'modal', target: "#enable-disable-agents"}, class: "btn btn-default", id: "enable-all" %>
        <%= link_to icon_tag('glyphicon-pause') + 'Disable all Agents', '#', data: { toggle: 'modal', target: "#enable-disable-agents"}, class: "btn btn-default", id: "disable-all" %>
      </div>
    </div>
  </div>
</div>
<%= render 'scenarios/confirm_deletion_modal', scenario: @scenario %>
<%= render 'scenarios/enable_agents_modal', scenario: @scenario %>