config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_scenario
      delete :remove_events
      delete :memory, action: :destroy_memory
    end

    collection do
      put :toggle_visibility
      post :propagate
      get :type_details
      get :event_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end

    resources :events, :only => [:index]

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resource :diagram, :only => [:show]

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :scenarios do
    collection do
      resource :scenario_imports, :only => [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
    end

    resource :diagram, :only => [:show]
  end

  resources :user_credentials, :except => :show do
    collection do
      post :import
    end
  end

  resources :services, :only => [:index, :destroy] do
    member do
      post :toggle_availability
    end
  end

  resources :jobs, :only => [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get "/worker_status" => "worker_status#show"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests, :via => [:get, :post, :put, :delete]
  post  "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy
  post  "/users/:user_id/update_location/:secret" => "web_requests#update_location" # legacy

  devise_for :users,
             controllers: { 
               omniauth_callbacks: 'omniauth_callbacks',
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "/about" => "home#about"
  root :to => "home#index"
end

app/models/user.rb
# Huginn is designed to be a multi-User system.  Users have many Agents (and Events created by those Agents).
class User < ActiveRecord::Base
  DEVISE_MODULES = [:database_authenticatable, :registerable,
                    :recoverable, :rememberable, :trackable,
                    :validatable, :lockable, :omniauthable,
                    (ENV['REQUIRE_CONFIRMED_EMAIL'] == 'true' ? :confirmable : nil)].compact
  devise *DEVISE_MODULES

  INVITATION_CODES = [ENV['INVITATION_CODE'] || 'try-huginn']

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates_presence_of :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, :with => /\A[a-zA-Z0-9_-]{3,190}\Z/, :message => "can only contain letters, numbers, underscores, and dashes, and must be between 3 and 190 characters in length."
  validates_inclusion_of :invitation_code, :on => :create, :in => INVITATION_CODES, :message => "is not valid", if: -> { !requires_no_invitation_code? && User.using_invitation_code? }

  has_many :user_credentials, :dependent => :destroy, :inverse_of => :user
  has_many :events, -> { order("events.created_at desc") }, :dependent => :delete_all, :inverse_of => :user
  has_many :agents, -> { order("agents.created_at desc") }, :dependent => :destroy, :inverse_of => :user
  has_many :logs, :through => :agents, :class_name => "AgentLog"
  has_many :scenarios, :inverse_of => :user, :dependent => :destroy
  has_many :services, -> { by_name('asc') }, :dependent => :destroy

  def available_services
    Service.available_to_user(self).by_name
  end

  # Allow users to login via either email or username.
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def active?
    !deactivated_at
  end

  def deactivate!
    User.transaction do
      agents.update_all(deactivated: true)
      update_attribute(:deactivated_at, Time.now)
    end
  end

  def activate!
    User.transaction do
      agents.update_all(deactivated: false)
      update_attribute(:deactivated_at, nil)
    end
  end

  def active_for_authentication?
    super && active?
  end

  def inactive_message
    active? ? super : :deactivated_account
  end

  def self.using_invitation_code?
    ENV['SKIP_INVITATION_CODE'] != 'true'
  end

  def requires_no_invitation_code!
    @requires_no_invitation_code = true
  end

  def requires_no_invitation_code?
    !!@requires_no_invitation_code
  end

  def undefined_agent_types
    agents.reorder('').group(:type).pluck(:type).select do |type|
      begin
        type.constantize
        false
      rescue NameError
        true
      end
    end
  end

  def undefined_agents
    agents.where(type: undefined_agent_types).select('id, schedule, events_count, type as undefined')
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!, except: [:switch_back]

  before_action :find_user, only: [:edit, :destroy, :update, :deactivate, :activate, :switch_to_user]

  helper_method :resource

  def index
    @users = User.reorder('created_at DESC').page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.requires_no_invitation_code!

    respond_to do |format|
      if @user.save
        DefaultScenarioImporter.import(@user)    
        format.html { redirect_to admin_users_path, notice: "User '#{@user.username}' was successfully created." }
        format.json { render json: @user, status: :ok, location: admin_users_path(@user) }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    params[:user].extract!(:password, :password_confirmation) if params[:user][:password].blank?
    @user.assign_attributes(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: "User '#{@user.username}' was successfully updated." }
        format.json { render json: @user, status: :ok, location: admin_users_path(@user) }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: "User '#{@user.username}' was deleted." }
      format.json { head :no_content }
    end
  end

  def deactivate
    @user.deactivate!

    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: "User '#{@user.username}' was deactivated." }
      format.json { render json: @user, status: :ok, location: admin_users_path(@user) }
    end
  end

  def activate
    @user.activate!

    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: "User '#{@user.username}' was activated." }
      format.json { render json: @user, status: :ok, location: admin_users_path(@user) }
    end
  end

  # allow an admin to sign-in as any other user

  def switch_to_user
    if current_user != @user
      old_user = current_user
      bypass_sign_in(@user)
      session[:original_admin_user_id] = old_user.id
    end
    redirect_to agents_path
  end

  def switch_back
    if session[:original_admin_user_id].present?
      bypass_sign_in(User.find(session[:original_admin_user_id]))
      session.delete(:original_admin_user_id)
    else
      redirect_to(root_path, alert: 'You must be an admin acting as a different user to do that.') and return
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :admin)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def resource
    @user
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    after_action :create_default_scenario, only: :create

    private

    def create_default_scenario
      DefaultScenarioImporter.import(@user) if @user.persisted?
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_account_state(user)
    if !user.active?
      content_tag :span, 'inactive', class: 'label label-danger'
    elsif user.access_locked?
      content_tag :span, 'locked', class: 'label label-danger'
    elsif ENV['REQUIRE_CONFIRMED_EMAIL'] == 'true' && !user.confirmed?
      content_tag :span, 'unconfirmed', class: 'label label-warning'
    else
      content_tag :span, 'active', class: 'label label-success'
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user], html: { class: 'form-horizontal' }) do |f| %>
  <%= devise_error_messages! %>
  <%= render partial: '/devise/registrations/common_registration_fields', locals: { f: f } %>

  <div class="form-group">
    <div class="col-md-offset-4 col-md-10">
      <%= f.label :admin do %>
        <%= f.check_box :admin %> Admin
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-4 col-md-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<hr>

<div class="row">
  <div class="col-md-12">
    <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, admin_users_path, class: "btn btn-default" %>
    <% if @user.persisted? && @user.active? && @user != current_user %>
      <%= link_to 'Become User', switch_to_user_admin_user_path(@user), class: "btn btn-default btn-info", data: { confirm: 'This will log you in as another user. Would you like to continue?' } %>
    <% end %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<% content_for :title, "Edit " + @user.username -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h2>Edit User</h2>

      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% content_for :title, "Users" -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>
          Users
        </h2>
      </div>

      <div class='table-responsive'>
        <table class='table table-striped events'>
          <tr>
            <th>Username</th>
            <th>Email</th>
            <th>State</th>
            <th>Active agents</th>
            <th>Deactivated agents</th>
            <th>Registered since</th>
            <th>Options</th>
          </tr>

          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.username, edit_admin_user_path(user) %></td>
              <td><%= user.email %></td>
              <td><%= user_account_state(user) %></td>
              <td><%= link_to user.agents.active.count, switch_to_user_admin_user_path(user), data: { confirm: 'This will log you in as another user. Would you like to continue?' } %></td>
              <td><%= link_to user.agents.inactive.count, switch_to_user_admin_user_path(user), data: { confirm: 'This will log you in as another user. Would you like to continue?' } %></td>
              <td title='<%= user.created_at %>'><%= time_ago_in_words user.created_at %> ago</td>
              <td>
                <div class="btn-group btn-group-xs">
                  <% if user != current_user %>
                    <% if user.active? %>
                      <%= link_to 'Become User', switch_to_user_admin_user_path(user), class: "btn btn-default", data: { confirm: 'This will log you in as another user. Would you like to continue?' } %>
                      <%= link_to 'Deactivate', deactivate_admin_user_path(user), method: :put, class: "btn btn-default" %>
                    <% else %>
                      <%= link_to 'Activate', activate_admin_user_path(user), method: :put, class: "btn btn-default" %>
                    <% end %>
                    <%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure? This can not be undone.' }, class: "btn btn-default" %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </table>
      </div>

      <%= paginate @users, theme: 'twitter-bootstrap-3' %>

      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-plus') + ' New User', new_admin_user_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<% content_for :title, "Create User" -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h2>Create new User</h2>

      <%= render partial: 'form' %>
    </div>
  </div>
</div>